# Specify a base image
FROM node:16-alpine

# Switch Workdir to /usr/app
WORKDIR /usr/app

# Copy our current directory into
# the container
COPY package.json .

# Install the dependencies
RUN npm install

COPY . .

# Default Command
CMD ["npm","run","serve"]